# Generated by Django 5.2.1 on 2025-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_exp', models.PositiveIntegerField()),
                ('specialisation', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('description', models.TextField()),
                ('advimg', models.ImageField(blank=True, null=True, upload_to='advimg/')),
            ],
        ),
    ]
