# Generated by Django 5.2.1 on 2025-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0002_alltypecases'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('family', 'FAMILY'), ('environmental', 'ENVIRONMENTAL'), ('bankrupty', 'BANKRUPTY'), ('tort', 'TORT'), ('child abuse', 'CHILD ABUSE'), ('labour law', 'LABOUR LAW'), ('administrative', 'ADMINISTRATIVE'), ('contract', 'CONTRACT'), ('other', 'OTHER')], max_length=100)),
                ('description', models.TextField()),
                ('any_document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
