# Generated by Django 5.2.1 on 2025-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0003_enquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('family', 'FAMILY'), ('environmental', 'ENVIRONMENTAL'), ('bankrupty', 'BANKRUPTY'), ('tort', 'TORT'), ('child abuse', 'CHILD ABUSE'), ('labour law', 'LABOUR LAW'), ('administrative', 'ADMINISTRATIVE'), ('contract', 'CONTRACT'), ('other', 'OTHER')], max_length=100)),
                ('description', models.TextField()),
                ('case_document', models.FileField(upload_to='')),
                ('total_no_hearing', models.IntegerField()),
                ('court_name', models.CharField(choices=[('supreme court', 'SUPREME COURT'), ('high court', 'HIGH COURT'), ('district court', 'DISTRICT COURT'), ('family court', 'FAMILY COURT'), ('civil court', 'CIVIL COURT'), ('criminal court', 'CRIMINAL COURT'), ('session court', 'SESSION COURT'), ('magistrate court', 'MAGISTRATE COURT'), ('consumer court', 'CONSUMER COURT'), ('labour court', 'LABOUR COURT')], max_length=100)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
