# Generated by Django 5.2.1 on 2025-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=models.IntegerField(default=500),
        ),
    ]
