# Generated by Django 5.2.1 on 2025-06-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmapp', '0005_alter_appointment_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawfirmapp.appointment')),
                ('lawyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyerdetail', to='lawfirmapp.lawyerdetails')),
            ],
        ),
    ]
